got.data: TCGA.RSEM GTEX.RSEM NETWORK

TCGA.RSEM:
	wget https://toil.xenahubs.net/download/tcga.RSEM.Hugo.norm.count -O TCGA.RSEM
GTEX.RSEM:
	wget https://toil.xenahubs.net/download/gtex.RSEM.Hugo.norm.count -O GTEX.RSEM
NETWORK:
	wget http://www.pathwaycommons.org/archives/PC2/v8/PathwayCommons.8.All.BINARY.SIF.hgnc.txt.sif.gz -O NETWORK
